plugins:
    - {name: static_map,        type: "costmap_2d::StaticLayer"}
    - {name: obstacles_laser,   type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,         type: "costmap_2d::InflationLayer"}

publish_frequency: 1.0

footprint: [[ 0.4,  0.35],
            [-0.4,  0.35],
            [-0.4, -0.35],
            [ 0.4, -0.35]]

transform_tolerance: 1
global_frame: map
robot_base_frame: base_link_robot
update_frequency: 1
planner_patience: 15

static_map:
    map_topic: map
    track_unknown_space: true

inflation:
    inflation_radius: 1.5

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /front_laser/scan, inf_is_valid: true}
