(cl:defpackage robot_door_closing-msg
  (:use )
  (:export
   "<DOOR_CLOSEACTION>"
   "DOOR_CLOSEACTION"
   "<DOOR_CLOSEACTIONFEEDBACK>"
   "DOOR_CLOSEACTIONFEEDBACK"
   "<DOOR_CLOSEACTIONGOAL>"
   "DOOR_CLOSEACTIONGOAL"
   "<DOOR_CLOSEACTIONRESULT>"
   "DOOR_CLOSEACTIONRESULT"
   "<DOOR_CLOSEFEEDBACK>"
   "DOOR_CLOSEFEEDBACK"
   "<DOOR_CLOSEGOAL>"
   "DOOR_CLOSEGOAL"
   "<DOOR_CLOSERESULT>"
   "DOOR_CLOSERESULT"
  ))

