; Auto-generated. Do not edit!


(cl:in-package robot_door_closing-msg)


;//! \htmlinclude door_closeFeedback.msg.html

(cl:defclass <door_closeFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass door_closeFeedback (<door_closeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <door_closeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'door_closeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_door_closing-msg:<door_closeFeedback> is deprecated: use robot_door_closing-msg:door_closeFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <door_closeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_door_closing-msg:status-val is deprecated.  Use robot_door_closing-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <door_closeFeedback>) ostream)
  "Serializes a message object of type '<door_closeFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <door_closeFeedback>) istream)
  "Deserializes a message object of type '<door_closeFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'status) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'status)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<door_closeFeedback>)))
  "Returns string type for a message object of type '<door_closeFeedback>"
  "robot_door_closing/door_closeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'door_closeFeedback)))
  "Returns string type for a message object of type 'door_closeFeedback"
  "robot_door_closing/door_closeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<door_closeFeedback>)))
  "Returns md5sum for a message object of type '<door_closeFeedback>"
  "672ccc7edd3a5621529e608443618e1f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'door_closeFeedback)))
  "Returns md5sum for a message object of type 'door_closeFeedback"
  "672ccc7edd3a5621529e608443618e1f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<door_closeFeedback>)))
  "Returns full string definition for message of type '<door_closeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32[] status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'door_closeFeedback)))
  "Returns full string definition for message of type 'door_closeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32[] status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <door_closeFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'status) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <door_closeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'door_closeFeedback
    (cl:cons ':status (status msg))
))
