// Auto-generated. Do not edit!

// (in-package robot_door_opening.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class door_openGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.door_name = null;
    }
    else {
      if (initObj.hasOwnProperty('door_name')) {
        this.door_name = initObj.door_name
      }
      else {
        this.door_name = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type door_openGoal
    // Serialize message field [door_name]
    bufferOffset = _serializer.string(obj.door_name, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type door_openGoal
    let len;
    let data = new door_openGoal(null);
    // Deserialize message field [door_name]
    data.door_name = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.door_name);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_door_opening/door_openGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '88b02874338f3a3a7c1bc8827afa90f2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    string door_name
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new door_openGoal(null);
    if (msg.door_name !== undefined) {
      resolved.door_name = msg.door_name;
    }
    else {
      resolved.door_name = ''
    }

    return resolved;
    }
};

module.exports = door_openGoal;
