// Generated by gencpp from file robot_door_closing/door_closeGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_DOOR_CLOSING_MESSAGE_DOOR_CLOSEGOAL_H
#define ROBOT_DOOR_CLOSING_MESSAGE_DOOR_CLOSEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_door_closing
{
template <class ContainerAllocator>
struct door_closeGoal_
{
  typedef door_closeGoal_<ContainerAllocator> Type;

  door_closeGoal_()
    : door_name()  {
    }
  door_closeGoal_(const ContainerAllocator& _alloc)
    : door_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _door_name_type;
  _door_name_type door_name;





  typedef boost::shared_ptr< ::robot_door_closing::door_closeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_door_closing::door_closeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct door_closeGoal_

typedef ::robot_door_closing::door_closeGoal_<std::allocator<void> > door_closeGoal;

typedef boost::shared_ptr< ::robot_door_closing::door_closeGoal > door_closeGoalPtr;
typedef boost::shared_ptr< ::robot_door_closing::door_closeGoal const> door_closeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_door_closing::door_closeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_door_closing::door_closeGoal_<ContainerAllocator1> & lhs, const ::robot_door_closing::door_closeGoal_<ContainerAllocator2> & rhs)
{
  return lhs.door_name == rhs.door_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_door_closing::door_closeGoal_<ContainerAllocator1> & lhs, const ::robot_door_closing::door_closeGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_door_closing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_door_closing::door_closeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_door_closing::door_closeGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_door_closing::door_closeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88b02874338f3a3a7c1bc8827afa90f2";
  }

  static const char* value(const ::robot_door_closing::door_closeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88b02874338f3a3aULL;
  static const uint64_t static_value2 = 0x7c1bc8827afa90f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_door_closing/door_closeGoal";
  }

  static const char* value(const ::robot_door_closing::door_closeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"string door_name\n"
;
  }

  static const char* value(const ::robot_door_closing::door_closeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.door_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct door_closeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_door_closing::door_closeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_door_closing::door_closeGoal_<ContainerAllocator>& v)
  {
    s << indent << "door_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.door_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_DOOR_CLOSING_MESSAGE_DOOR_CLOSEGOAL_H
