// Generated by gencpp from file robot_door_closing/door_closeResult.msg
// DO NOT EDIT!


#ifndef ROBOT_DOOR_CLOSING_MESSAGE_DOOR_CLOSERESULT_H
#define ROBOT_DOOR_CLOSING_MESSAGE_DOOR_CLOSERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_door_closing
{
template <class ContainerAllocator>
struct door_closeResult_
{
  typedef door_closeResult_<ContainerAllocator> Type;

  door_closeResult_()
    : status()  {
    }
  door_closeResult_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::robot_door_closing::door_closeResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_door_closing::door_closeResult_<ContainerAllocator> const> ConstPtr;

}; // struct door_closeResult_

typedef ::robot_door_closing::door_closeResult_<std::allocator<void> > door_closeResult;

typedef boost::shared_ptr< ::robot_door_closing::door_closeResult > door_closeResultPtr;
typedef boost::shared_ptr< ::robot_door_closing::door_closeResult const> door_closeResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_door_closing::door_closeResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_door_closing::door_closeResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_door_closing::door_closeResult_<ContainerAllocator1> & lhs, const ::robot_door_closing::door_closeResult_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_door_closing::door_closeResult_<ContainerAllocator1> & lhs, const ::robot_door_closing::door_closeResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_door_closing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_door_closing::door_closeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_door_closing::door_closeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_door_closing::door_closeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_door_closing::door_closeResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_door_closing::door_closeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_door_closing::door_closeResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_door_closing::door_closeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::robot_door_closing::door_closeResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_door_closing::door_closeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_door_closing/door_closeResult";
  }

  static const char* value(const ::robot_door_closing::door_closeResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_door_closing::door_closeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"string status\n"
;
  }

  static const char* value(const ::robot_door_closing::door_closeResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_door_closing::door_closeResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct door_closeResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_door_closing::door_closeResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_door_closing::door_closeResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_DOOR_CLOSING_MESSAGE_DOOR_CLOSERESULT_H
