// Generated by gencpp from file rosserial_mbed/SyncGen.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_MBED_MESSAGE_SYNCGEN_H
#define ROSSERIAL_MBED_MESSAGE_SYNCGEN_H

#include <ros/service_traits.h>


#include <rosserial_mbed/SyncGenRequest.h>
#include <rosserial_mbed/SyncGenResponse.h>


namespace rosserial_mbed
{

struct SyncGen
{

typedef SyncGenRequest Request;
typedef SyncGenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncGen
} // namespace rosserial_mbed


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_mbed::SyncGen > {
  static const char* value()
  {
    return "ea9d83d55be0e52c11fc70f07c9af7d8";
  }

  static const char* value(const ::rosserial_mbed::SyncGen&) { return value(); }
};

template<>
struct DataType< ::rosserial_mbed::SyncGen > {
  static const char* value()
  {
    return "rosserial_mbed/SyncGen";
  }

  static const char* value(const ::rosserial_mbed::SyncGen&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_mbed::SyncGenRequest> should match
// service_traits::MD5Sum< ::rosserial_mbed::SyncGen >
template<>
struct MD5Sum< ::rosserial_mbed::SyncGenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_mbed::SyncGen >::value();
  }
  static const char* value(const ::rosserial_mbed::SyncGenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_mbed::SyncGenRequest> should match
// service_traits::DataType< ::rosserial_mbed::SyncGen >
template<>
struct DataType< ::rosserial_mbed::SyncGenRequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_mbed::SyncGen >::value();
  }
  static const char* value(const ::rosserial_mbed::SyncGenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_mbed::SyncGenResponse> should match
// service_traits::MD5Sum< ::rosserial_mbed::SyncGen >
template<>
struct MD5Sum< ::rosserial_mbed::SyncGenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_mbed::SyncGen >::value();
  }
  static const char* value(const ::rosserial_mbed::SyncGenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_mbed::SyncGenResponse> should match
// service_traits::DataType< ::rosserial_mbed::SyncGen >
template<>
struct DataType< ::rosserial_mbed::SyncGenResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_mbed::SyncGen >::value();
  }
  static const char* value(const ::rosserial_mbed::SyncGenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_MBED_MESSAGE_SYNCGEN_H
