// Generated by gencpp from file rosserial_mbed/SyncGenRequest.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_MBED_MESSAGE_SYNCGENREQUEST_H
#define ROSSERIAL_MBED_MESSAGE_SYNCGENREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosserial_mbed
{
template <class ContainerAllocator>
struct SyncGenRequest_
{
  typedef SyncGenRequest_<ContainerAllocator> Type;

  SyncGenRequest_()
    : frequency(0)  {
    }
  SyncGenRequest_(const ContainerAllocator& _alloc)
    : frequency(0)  {
  (void)_alloc;
    }



   typedef int32_t _frequency_type;
  _frequency_type frequency;





  typedef boost::shared_ptr< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SyncGenRequest_

typedef ::rosserial_mbed::SyncGenRequest_<std::allocator<void> > SyncGenRequest;

typedef boost::shared_ptr< ::rosserial_mbed::SyncGenRequest > SyncGenRequestPtr;
typedef boost::shared_ptr< ::rosserial_mbed::SyncGenRequest const> SyncGenRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator1> & lhs, const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator2> & rhs)
{
  return lhs.frequency == rhs.frequency;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator1> & lhs, const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosserial_mbed

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28a032761c91475f369a1e6b6a4c8553";
  }

  static const char* value(const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28a032761c91475fULL;
  static const uint64_t static_value2 = 0x369a1e6b6a4c8553ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_mbed/SyncGenRequest";
  }

  static const char* value(const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 frequency\n"
;
  }

  static const char* value(const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncGenRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_mbed::SyncGenRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_mbed::SyncGenRequest_<ContainerAllocator>& v)
  {
    s << indent << "frequency: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_MBED_MESSAGE_SYNCGENREQUEST_H
