(cl:defpackage robot_door_opening-msg
  (:use )
  (:export
   "<DOOR_OPENACTION>"
   "DOOR_OPENACTION"
   "<DOOR_OPENACTIONFEEDBACK>"
   "DOOR_OPENACTIONFEEDBACK"
   "<DOOR_OPENACTIONGOAL>"
   "DOOR_OPENACTIONGOAL"
   "<DOOR_OPENACTIONRESULT>"
   "DOOR_OPENACTIONRESULT"
   "<DOOR_OPENFEEDBACK>"
   "DOOR_OPENFEEDBACK"
   "<DOOR_OPENGOAL>"
   "DOOR_OPENGOAL"
   "<DOOR_OPENRESULT>"
   "DOOR_OPENRESULT"
  ))

