; Auto-generated. Do not edit!


(cl:in-package robot_door_opening-msg)


;//! \htmlinclude door_openResult.msg.html

(cl:defclass <door_openResult> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:string
    :initform ""))
)

(cl:defclass door_openResult (<door_openResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <door_openResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'door_openResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_door_opening-msg:<door_openResult> is deprecated: use robot_door_opening-msg:door_openResult instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <door_openResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_door_opening-msg:status-val is deprecated.  Use robot_door_opening-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <door_openResult>) ostream)
  "Serializes a message object of type '<door_openResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <door_openResult>) istream)
  "Deserializes a message object of type '<door_openResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<door_openResult>)))
  "Returns string type for a message object of type '<door_openResult>"
  "robot_door_opening/door_openResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'door_openResult)))
  "Returns string type for a message object of type 'door_openResult"
  "robot_door_opening/door_openResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<door_openResult>)))
  "Returns md5sum for a message object of type '<door_openResult>"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'door_openResult)))
  "Returns md5sum for a message object of type 'door_openResult"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<door_openResult>)))
  "Returns full string definition for message of type '<door_openResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'door_openResult)))
  "Returns full string definition for message of type 'door_openResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <door_openResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <door_openResult>))
  "Converts a ROS message object to a list"
  (cl:list 'door_openResult
    (cl:cons ':status (status msg))
))
