; Auto-generated. Do not edit!


(cl:in-package robot_door_opening-msg)


;//! \htmlinclude door_openGoal.msg.html

(cl:defclass <door_openGoal> (roslisp-msg-protocol:ros-message)
  ((door_name
    :reader door_name
    :initarg :door_name
    :type cl:string
    :initform ""))
)

(cl:defclass door_openGoal (<door_openGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <door_openGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'door_openGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_door_opening-msg:<door_openGoal> is deprecated: use robot_door_opening-msg:door_openGoal instead.")))

(cl:ensure-generic-function 'door_name-val :lambda-list '(m))
(cl:defmethod door_name-val ((m <door_openGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_door_opening-msg:door_name-val is deprecated.  Use robot_door_opening-msg:door_name instead.")
  (door_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <door_openGoal>) ostream)
  "Serializes a message object of type '<door_openGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'door_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'door_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <door_openGoal>) istream)
  "Deserializes a message object of type '<door_openGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'door_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'door_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<door_openGoal>)))
  "Returns string type for a message object of type '<door_openGoal>"
  "robot_door_opening/door_openGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'door_openGoal)))
  "Returns string type for a message object of type 'door_openGoal"
  "robot_door_opening/door_openGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<door_openGoal>)))
  "Returns md5sum for a message object of type '<door_openGoal>"
  "88b02874338f3a3a7c1bc8827afa90f2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'door_openGoal)))
  "Returns md5sum for a message object of type 'door_openGoal"
  "88b02874338f3a3a7c1bc8827afa90f2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<door_openGoal>)))
  "Returns full string definition for message of type '<door_openGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string door_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'door_openGoal)))
  "Returns full string definition for message of type 'door_openGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string door_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <door_openGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'door_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <door_openGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'door_openGoal
    (cl:cons ':door_name (door_name msg))
))
