TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_rotational_vel: 0.7
  min_in_place_rotational_vel: 0.4

  acc_lim_theta: 1.2
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  holonomic_robot: false
  meter_scoring: true
  pdist_scale: 0.5
  gdist_scale: 0.6
  
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  
  dwa: false
